### ISSUE TITLE
not sure the code to avoid updating a module twice works

### ISSUE THREAD

**Issue by gurneyalex** [camptocamp/marabunta#24]
check the build time of the master branch on  https://travis-ci.com/camptocamp/roctool_odoo/builds (private repo) : it goes down from ~30min on build 666 to ~20min on build 668 when I merged the refactoring of the setup

**Comment by gurneyalex** [comment]
@guewen I opened this issue after our discussion during odoo experience

**Comment by guewen** [comment]
@gurneyalex not tested but from a reading of the code, I suspect that it might be related to dependencies unlisted in migration.yml. The addons are excluded from further updates only if they are explicitly listed in a version.

This migration file would install addons up to `sale`, and run again `-u base`  on 10.1.0
```
migration:
  options:
    install_command: odoo
  versions:
    - version: 10.0.0
      addons:
        upgrade:
          - sale
    - version: 10.1.0
      addons:
        upgrade:
          - base
```

This migration file would install skip updates in 10.1.0:
```
migration:
  options:
    install_command: odoo
  versions:
    - version: 10.0.0
      addons:
        upgrade:
          - base
          - sale
    - version: 10.1.0
      addons:
        upgrade:
          - base
```

If this is the issue, we might want to get all the dependencies of an installed or upgraded addon and exclude them for further upgrades.
