### ISSUE TITLE
Step ignored when same steps are defined in the same version 

### ISSUE THREAD

**Issue by grindtildeath** [camptocamp/marabunta#45]
Context :
When there are multiple **same** steps defined for the same version, the first one is ignored.

Example :
``` 
version v.w.x.y.z:
operations:
  pre:
    - anthem songs.script_pre::main
addons:
  update:
    - my_beautiful_module
operations:
  post:
    - anthem songs.script_post::main
```
With such a migration step, running version v.w.x.y.z will only execute `anthem songs.script_post::main` as post and won't execute `anthem songs.script_pre::main` ! :warning: 

IMO in such cases marabunta must raise an error instead of ignoring a script, leaving the user wondering why his script was not executed.
